# Generated by Django 2.2.7 on 2019-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='update_at',
            new_name='modified_at',
        ),
    ]
