# Generated by Django 2.2.7 on 2019-11-17 10:57

import class_path_web.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191117_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=class_path_web.content.models.upload_file_path),
        ),
    ]
