# Generated by Django 2.2.7 on 2019-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20191117_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityanswer',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_multimidia',
            field=models.BooleanField(default=False),
        ),
    ]
