# Generated by Django 2.2.7 on 2019-12-14 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20191204_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_multimidia',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='teacher',
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='multimedia_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityanswer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 14, 8, 45, 12, 91736, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityanswer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
