# Generated by Django 2.2.7 on 2019-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20191214_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='update_at',
            new_name='modified_at',
        ),
    ]
