# Generated by Django 2.2.7 on 2020-01-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191230_0230'),
        ('content', '0006_auto_20191214_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
        migrations.AddField(
            model_name='content',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='accounts.Teacher'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
