# Generated by Django 2.2.7 on 2020-01-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191230_0230'),
        ('content', '0007_auto_20200103_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.Class'),
        ),
    ]
