# Generated by Django 2.2.7 on 2020-01-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200109_0602'),
        ('content', '0009_auto_20200109_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='class_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.Course'),
        ),
    ]
