# Generated by Django 2.2.7 on 2020-01-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200118_0433'),
        ('content', '0010_auto_20200111_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.Class'),
        ),
    ]
