# Generated by Django 2.2.7 on 2019-11-13 06:53

import class_path_web.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', class_path_web.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
