# Generated by Django 2.2.7 on 2019-11-13 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191113_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='cpf'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='cpf')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='full name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='accounts.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
