# Generated by Django 2.2.7 on 2019-11-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191113_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
