# Generated by Django 2.2.7 on 2019-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191214_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='is_admin'),
        ),
    ]
