# Generated by Django 2.2.7 on 2019-12-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191217_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Institution'),
        ),
    ]
