# Generated by Django 2.2.7 on 2019-12-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191228_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.Institution'),
        ),
    ]
