# Generated by Django 2.2.7 on 2019-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191229_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
