# Generated by Django 2.2.7 on 2020-01-18 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200109_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.Program'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_institution',
            field=models.BooleanField(default=True, verbose_name='has institution'),
        ),
        migrations.AlterField(
            model_name='class',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.Teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='accounts.Institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is admin'),
        ),
    ]
